name: Test Routing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system Ruby
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev

    - name: Verify Ruby Version
      run: ruby -v

    - name: Run Payment Router
      run: |
        ruby router.rb data/providers.json data/operations_queue_10.json routing_decisions.json routing_report.json

    - name: Validate Decisions
      run: |
        ruby scripts/validate_10.rb routing_decisions.json
